import { jsPDF } from "jspdf";

export const generateHealthReport = (analysisData, chatHistory, uploadedImage) => {
  const doc = new jsPDF();
  const date = new Date().toLocaleString();

  // Title
  doc.setFontSize(22);
  doc.setTextColor(40, 40, 100);
  doc.text("AI Healthcare Analysis Report", 20, 20);

  // Metadata
  doc.setFontSize(10);
  doc.setTextColor(100);
  doc.text(`Generated on: ${date}`, 20, 30);
  doc.text("Generated by: AI Healthcare Chatbot", 20, 35);

  // Disclaimer
  doc.setTextColor(200, 50, 50);
  doc.setFontSize(8);
  doc.text("DISCLAIMER: This report is generated by an AI and is for general guidance only. Consult a doctor.", 20, 45);

  let yPos = 60;

  // Analysis Result
  doc.setFontSize(14);
  doc.setTextColor(0);
  doc.text("Analysis Summary:", 20, yPos);
  yPos += 10;
  
  doc.setFontSize(10);
  const splitText = doc.splitTextToSize(analysisData, 170);
  doc.text(splitText, 20, yPos);
  yPos += splitText.length * 5 + 10;

  // Chat Summary
  doc.setFontSize(14);
  doc.text("Chat Summary:", 20, yPos);
  yPos += 10;
  
  doc.setFontSize(10);
  chatHistory.slice(-5).forEach((msg) => {
    if (yPos > 270) {
      doc.addPage();
      yPos = 20;
    }
    const role = msg.role === "user" ? "User" : "AI";
    const text = `${role}: ${msg.content.substring(0, 100)}${msg.content.length > 100 ? '...' : ''}`;
    doc.text(text, 20, yPos);
    yPos += 7;
  });

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(150);
  doc.text("End of Report", 105, 290, { align: "center" });

  doc.save(`Health_Report_${new Date().getTime()}.pdf`);
};
